### PR TITLE
Switch scout agent on and of via crontab

### PR DESCRIPTION
**Pull request by sevaine**
Add functionality to cater for scout agent 'enable/disable' in this module.

```puppet
$enable = false ( crontab absent )
default:
  $enable = true ( crontab present )
```

### CODE REVIEW

**Comment by BenAlexanders** [comment]
:+1: on green

**Comment by sevaine** [comment]
Yeah - about that...

```
Finished in 0.00008 seconds
0 examples, 0 failures
** Invoke spec_clean (first_time)
** Execute spec_clean
** Invoke metadata (first_time)
** Execute metadata
metadata-json-lint metadata.json
Warning: Dependency puppetlabs-stdlib has an open ended dependency version requirement >= 1.0.0
Warning: License identifier MIT License (MIT) is not in the SPDX list: http://spdx.org/licenses/
Errors found in metadata.json
rake aborted!
Command failed with status (1): [metadata-json-lint metadata.json...]
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/home/travis/build/envato/puppet-scout/Rakefile:37:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `load'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/rake:23:in `<main>'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test => metadata
The command "bundle exec rake test --trace" exited with 1.
Done. Your build exited with 1.```

**Comment by johnsyweb** [comment]
:+1:

**Comment by sevaine** [comment]
re-running specs on this branch then checking the diffs between it and origin/master

**Comment by denmat** [comment]
no longer relevant

**Pull request closed without merging**
